language: d

d:
  - dmd-2.067.1
#  - ldc-0.16.0

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers

script:
# examples
  - dub run --build=coverage --compiler=${DC} :algebra -- 32
  - dub run --build=coverage --compiler=${DC} :bp -- 32
# current compilers both dmd and ldc run over the 3G memory limit
#  - dub run --build=coverage --compiler=${DC} :nw -- 32 10
# unit tests run after examples to collect more coverage
  - dub test --build=testing --compiler=${DC} :compiler
  - dub test --build=testing --compiler=${DC} :runtime

after_success:
  - dub build --build=release --compiler=${DC} :coverall
  - tools/bin/clop_coverall

# Local Variables:
# compile-command: "dub --build=verbose :nw -- 32 10"
# End:
