sudo: required
dist: trusty
language: d

d:
  - dmd
#  - ldc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq opencl-headers
  - export AMDAPPSDKROOT=${HOME}/AMDAPPSDK
  - export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors
  - export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
  - bash .travis/amd_sdk.sh
  - tar -xjf AMD-SDK.tar.bz2
  - mkdir -p ${OPENCL_VENDOR_PATH}
  - sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT}
  - echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd
  - chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo
  - ${AMDAPPSDKROOT}/bin/x86_64/clinfo

script:
# examples
  - dub run --build=coverage --compiler=${DC} :algebra -- 32
  - dub run --build=coverage --compiler=${DC} :bp -- 32
# current compilers both dmd and ldc run over the 3G memory limit
#  - dub run --build=coverage --compiler=${DC} :nw -- 32 10
  - dub run --build=coverage --compiler=${DC} :wrapper_example
# unit tests run after examples to collect more coverage
  - dub test --build=testing --compiler=${DC} :compiler
  - dub test --build=testing --compiler=${DC} :runtime

after_success:
  - dub build --build=release --compiler=${DC} :coverall
  - tools/bin/clop_coverall

# Local Variables:
# compile-command: "dub --build=verbose :nw -- 32 10"
# End:
