language: d

d:
  - dmd-2.067.0
#  - ldc-0.15.1

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers

script:
#  - dub test --build=testing --compiler=${DC} :compiler
  - dub test --build=testing --compiler=${DC} :runtime
  - dub run --build=coverage --compiler=${DC} :algebra -- 32
  - dub run --build=coverage --compiler=${DC} :bp -- 32
  - dub run --build=coverage --compiler=${DC} :nw -- 32 10

after_success:
  - dub build --build=release --compiler=${DC} :coverall
  - tools/bin/clop_coverall

# Local Variables:
# compile-command: "dub --build=verbose :nw -- 32 10"
# End:
