language: d

d:
  - ldc-0.15.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers

script:
  - dub --compiler=ldc2 --build=debug :nw -- 32 10
