language: d

d:
  - dmd-2.067.0
#  - ldc-0.15.1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers

script:
  - dub run --build=release --compiler=${DC} :algebra -- 32
  - dub run --build=release --compiler=${DC} :bp -- 32
  - dub run --build=release --compiler=${DC} :nw -- 32 10

# Local Variables:
# compile-command: "dub --build=verbose :nw -- 32 10"
# End:
